/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AgreementIdRouteImport } from './routes/agreement.$id'
import { Route as AgreementNewRouteImport } from './routes/agreement.new'
import { Route as AgreementVaultRouteImport } from './routes/agreement.vault'
import { Route as ProIdRouteImport } from './routes/pro.$id'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as StayIdRouteImport } from './routes/stay.$id'
import { Route as AgreementPdfIdRouteImport } from './routes/agreement.pdf.$id'
import { Route as AgreementRenewIdRouteImport } from './routes/agreement.renew.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementIdRoute = AgreementIdRouteImport.update({
  id: '/agreement/$id',
  path: '/agreement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementNewRoute = AgreementNewRouteImport.update({
  id: '/agreement/new',
  path: '/agreement/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementVaultRoute = AgreementVaultRouteImport.update({
  id: '/agreement/vault',
  path: '/agreement/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIdRoute = ProIdRouteImport.update({
  id: '/pro/$id',
  path: '/pro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StayIdRoute = StayIdRouteImport.update({
  id: '/stay/$id',
  path: '/stay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementPdfIdRoute = AgreementPdfIdRouteImport.update({
  id: '/agreement/pdf/$id',
  path: '/agreement/pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRenewIdRoute = AgreementRenewIdRouteImport.update({
  id: '/agreement/renew/$id',
  path: '/agreement/renew/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/agreement/$id': typeof AgreementIdRoute
  '/agreement/new': typeof AgreementNewRoute
  '/agreement/vault': typeof AgreementVaultRoute
  '/pro/$id': typeof ProIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/stay/$id': typeof StayIdRoute
  '/agreement/pdf/$id': typeof AgreementPdfIdRoute
  '/agreement/renew/$id': typeof AgreementRenewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/agreement/$id': typeof AgreementIdRoute
  '/agreement/new': typeof AgreementNewRoute
  '/agreement/vault': typeof AgreementVaultRoute
  '/pro/$id': typeof ProIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/stay/$id': typeof StayIdRoute
  '/agreement/pdf/$id': typeof AgreementPdfIdRoute
  '/agreement/renew/$id': typeof AgreementRenewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agreements': typeof AgreementsRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/agreement/$id': typeof AgreementIdRoute
  '/agreement/new': typeof AgreementNewRoute
  '/agreement/vault': typeof AgreementVaultRoute
  '/pro/$id': typeof ProIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/stay/$id': typeof StayIdRoute
  '/agreement/pdf/$id': typeof AgreementPdfIdRoute
  '/agreement/renew/$id': typeof AgreementRenewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreements'
    | '/booking'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/services'
    | '/signup'
    | '/agreement/$id'
    | '/agreement/new'
    | '/agreement/vault'
    | '/pro/$id'
    | '/property/$id'
    | '/stay/$id'
    | '/agreement/pdf/$id'
    | '/agreement/renew/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreements'
    | '/booking'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/services'
    | '/signup'
    | '/agreement/$id'
    | '/agreement/new'
    | '/agreement/vault'
    | '/pro/$id'
    | '/property/$id'
    | '/stay/$id'
    | '/agreement/pdf/$id'
    | '/agreement/renew/$id'
  id:
    | '__root__'
    | '/'
    | '/agreements'
    | '/booking'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/reviews'
    | '/services'
    | '/signup'
    | '/agreement/$id'
    | '/agreement/new'
    | '/agreement/vault'
    | '/pro/$id'
    | '/property/$id'
    | '/stay/$id'
    | '/agreement/pdf/$id'
    | '/agreement/renew/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgreementsRoute: typeof AgreementsRoute
  BookingRoute: typeof BookingRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  AgreementIdRoute: typeof AgreementIdRoute
  AgreementNewRoute: typeof AgreementNewRoute
  AgreementVaultRoute: typeof AgreementVaultRoute
  ProIdRoute: typeof ProIdRoute
  PropertyIdRoute: typeof PropertyIdRoute
  StayIdRoute: typeof StayIdRoute
  AgreementPdfIdRoute: typeof AgreementPdfIdRoute
  AgreementRenewIdRoute: typeof AgreementRenewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement/$id': {
      id: '/agreement/$id'
      path: '/agreement/$id'
      fullPath: '/agreement/$id'
      preLoaderRoute: typeof AgreementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement/new': {
      id: '/agreement/new'
      path: '/agreement/new'
      fullPath: '/agreement/new'
      preLoaderRoute: typeof AgreementNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement/vault': {
      id: '/agreement/vault'
      path: '/agreement/vault'
      fullPath: '/agreement/vault'
      preLoaderRoute: typeof AgreementVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$id': {
      id: '/pro/$id'
      path: '/pro/$id'
      fullPath: '/pro/$id'
      preLoaderRoute: typeof ProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay/$id': {
      id: '/stay/$id'
      path: '/stay/$id'
      fullPath: '/stay/$id'
      preLoaderRoute: typeof StayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement/pdf/$id': {
      id: '/agreement/pdf/$id'
      path: '/agreement/pdf/$id'
      fullPath: '/agreement/pdf/$id'
      preLoaderRoute: typeof AgreementPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement/renew/$id': {
      id: '/agreement/renew/$id'
      path: '/agreement/renew/$id'
      fullPath: '/agreement/renew/$id'
      preLoaderRoute: typeof AgreementRenewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgreementsRoute: AgreementsRoute,
  BookingRoute: BookingRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  AgreementIdRoute: AgreementIdRoute,
  AgreementNewRoute: AgreementNewRoute,
  AgreementVaultRoute: AgreementVaultRoute,
  ProIdRoute: ProIdRoute,
  PropertyIdRoute: PropertyIdRoute,
  StayIdRoute: StayIdRoute,
  AgreementPdfIdRoute: AgreementPdfIdRoute,
  AgreementRenewIdRoute: AgreementRenewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
